# Generated by Django 5.1.6 on 2025-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
