# Generated by Django 5.1.6 on 2025-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0002_allergy_facialrecognitiondata_item_itemallergy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('worker', 'Worker'), ('admin', 'Admin')], max_length=10),
        ),
    ]
