# Generated by Django 5.1.6 on 2025-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0004_user_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
