# Generated by Django 5.1.6 on 2025-03-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0006_faceembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FacePay.user'),
        ),
    ]
