# Generated by Django 5.1.7 on 2025-03-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0007_remove_faceembedding_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceembedding',
            name='user',
        ),
        migrations.AddField(
            model_name='faceembedding',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='FacePay.student'),
            preserve_default=False,
        ),
    ]
