# Generated by Django 5.1.7 on 2025-03-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacePay.user'),
        ),
    ]
