# Generated by Django 5.1.7 on 2025-03-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacePay', '0010_remove_transaction_item_transaction_cart_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='parent',
        ),
    ]
